version: '2.3'

services: 

  docker-mysql:

    image: mysql:5.7

    environment:

      - MYSQL_ROOT_PASSWORD=rootpass

      - MYSQL_DATABASE=lab5 

      - MYSQL_PASSWORD=andrei

  spring-boot-app:

    image: hello-app-sql

    depends_on:

      - docker-mysql

    ports:

      - 8080:8080

    environment:

      - DATABASE_HOST=docker-mysql

      - DATABASE_USER=andrei

      - DATABASE_PASSWORD=andrei

      - DATABASE_NAME=lab5 

      - DATABASE_PORT=3306